#cloud-config
hostname: worker
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/84a4a7a07bab83c044d397549cec4e9e
    proxy: on

  fleet:
      public-ip: $public_ipv4
      metadata: "role=worker,provider=digitialocean"
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

  update:
    reboot-strategy: etcd-lock

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeXdXjlb2Pqr6r2LKYiO7pA5ImhTmawD7K+PzbqXk9G4U7YiHowZLd0RONdSA4D16W35BFbTPhfnTre0x6SKhIJXhpIrAqyC96f/67rAPWH5B740F6RUSGjDu9D0ck6F66PUnnbWLhVjNtvZT+gIpRrlk+5WjZp4vNv5V00UrKUAtynd7rDwxyikT9ds0HzSXGDWG2REKdmEVIigsFhHw9MGEKoPTXOXskK8fOOszdXY6PLi9B8Mhmt8F07NvG0Zn8RU73HY3TXWY8jd3FtHhfSpYznzWJlE5zjcIyhPw+dqu0gfU8ijdZMBiAqTWsxQxiz6LZ4wwTr/Zp8XUQkKOF

write_files:
  - path: /home/core/.bashrc
    owner: core:core
    permissions: 0655
    content: |
      # Test for an interactive shell.  There is no need to set anything
      # past this point for scp and rcp, and it's important to refrain from
      # outputting anything in those cases.
      if [[ $- != *i* ]] ; then
      	# Shell is non-interactive.  Be done now!
      	return
      fi
      # Put your fun stuff here.
      alias csysdig="docker run -i -t --rm --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro sysdig/sysdig csysdig -pc"
      alias sysdig="docker run -i -t --rm --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro sysdig/sysdig sysdig"
